spam_keywords = [
    "free",
    "click here",
    "subscribe",
    "buy now",
    "limited time offer",
    "act now",
    "call now",
    "exclusive deal",
    "winner",
    "congratulations",
    "claim your prize",
    "visit our website",
    "don't miss out",
    "order now",
    "guaranteed",
    "100% free",
    "risk-free",
    "credit card",
    "earn money",
    "make money",
    "work from home",
    "get rich",
    "instant access",
    "no cost",
    "low cost",
    "cheap",
    "discount",
    "clearance",
    "deal",
    "bargain",
    "offer",
    "urgent",
    "important",
    "alert",
    "save big",
    "save money",
    "limited supply",
    "supplies are limited",
    "while supplies last",
    "special promotion",
    "click the link",
    "visit our site",
    "win",
    "winning",
    "prize",
    "award",
    "gift",
    "bonus",
    "free trial",
    "trial offer",
    "money-back guarantee",
    "satisfaction guaranteed",
    "no obligation",
    "easy terms",
    "fast cash",
    "fast money",
    "get paid",
    "extra income",
    "residual income",
    "be your own boss",
    "work at home",
    "online biz op",
    "email marketing",
    "seo",
    "search engine optimization",
    "internet marketing",
    "social media marketing",
    "internet biz",
    "online business",
    "home business",
    "internet business",
    "clickbank",
    "forex",
    "weight loss",
    "lose weight",
    "fat loss",
    "diet",
    "nutrition",
    "supplements",
    "pills",
    "miracle cure",
    "cure",
    "pharmacy",
    "medication",
    "drugs",
    "viagra",
    "cialis",
    "levitra",
    "casino",
    "gambling",
    "betting",
    "poker",
    "slots",
    "bingo",
    "jackpot",
    "lottery",
    "sweepstakes",
    "dating",
    "singles",
    "meet singles",
    "adult",
    "xxx",
    "porn",
    "sex",
    "nude",
    "naked",
    "loan",
    "mortgage",
    "debt",
    "consolidation",
    "bankruptcy",
    "investment",
    "stocks",
    "bonds",
    "trading",
    "broker",
    "retirement",
    "pension",
    "mutual fund",
    "real estate",
    "property",
    "luxury",
    "finance",
    "financial",
    "credit score",
    "credit report",
    "free credit",
    "repair your credit",
    "credit repair",
    "credit card debt",
    "bad credit",
    "good credit",
    "zero percent",
    "low interest",
    "refinance",
    "refinancing",
    "car loan",
    "auto loan",
    "student loan",
    "payday loan",
    "cash advance",
    "apply now",
    "get approved",
    "approval",
    "approved",
    "funding",
    "grant",
    "grants",
    "scholarship",
    "scholarships",
    "money",
    "cash",
    "payday",
    "consolidate",
    "consolidation",
    "eliminate debt",
    "reduce debt",
    "debt relief",
    "save thousands",
    "personal loan",
    "business loan",
    "loan approval",
    "loan offers",
    "loan rates",
    "best rates",
    "lowest rates",
    "mortgage rates",
    "mortgage refinance",
    "home loan",
    "bad credit loan",
    "credit score"
]
def check_spam(comment):
    check = False
    for keyword in spam_keywords:
        if keyword.lower() in comment:
            check = True
            break
    if check:
        print("This is a spam comment")
    else:
        print("Not a spam comment")
            
comment = input("enter comment: ")
check_spam(comment.lower())
